apiVersion: v1
kind: Pod
metadata:
  name: boostrap-1
  labels:
    app: boostrap-1
spec:
  containers:
  - name: hello-world
    image: samber/hello-world-nodejs
    env:
      - name: PORT
        value: "8080"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080