apiVersion: v1
kind: Pod
metadata:
  name: bootstrap-1
  namespace: bootstrap1
  labels:
    app: bootstrap-1
spec:
  containers:
  - name: hello-world
    image: samber/hello-world-nodejs
    env:
      - name: PORT
        value: "8080"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080 

---

apiVersion: v1
kind: Service
metadata:
  name: bootstrap-1-service
  namespace: bootstrap1
spec:
  type: LoadBalancer
  selector:
    app: bootstrap-1
  ports:
  - port: 8085
    targetPort: 8080

---

kind: PersistentVolume
apiVersion: v1
metadata:
      name: pv01
spec:
   capacity: # defines the capacity of PV we are creating
       storage: 512m #the amount of storage we are tying to claim
   accessModes: # defines the rights of the volume we are creating
      - ReadWriteOnce
   hostPath:
        path: "/tmp/data01" # path to which we are creating the volume
