apiVersion: v1
kind: Pod
metadata:
  name: bootstrap-1
  namespace: bootstrap1
  labels:
    app: bootstrap-1
spec:
  containers:
  - name: hello-world
    image: samber/hello-world-nodejs
    env:
      - name: PORT
        value: "8080"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: bootstrap-1-service
  namespace: bootstrap1
spec:
  type: LoadBalancer
  selector:
    app: bootstrap-1
  ports:
  - port: 8085
    targetPort: 8080
