apiVersion: v1
kind: Pod
metadata:
  name: boostrap-1
  namespace: boostrap1
spec:
  containers:
  - name: hello-world
    image: samber/hello-world-nodejs
    env:
      - name: PORT
        value: "8080"