apiVersion: v1
kind: Pod
metadata:
  name: boostrap-1
  namespace: boostrap1
  labels:
    app: boostrap-1
spec:
  containers:
  - name: hello-world
    image: samber/hello-world-nodejs
    env:
      - name: PORT
        value: "8080"

--- 

apiVersion: v1
kind: Service
metadata:
  name: boostrap-1-service
spec:
  selector:
    app: boostrap-1
  ports:
  - protocol:
    port: 8080
    targetPort: 8085