apiVersion: v1
kind: Pod
metadata:
  name: boostrap-1
  namespace: boostrap1
  labels:
    app: boostrap-1
spec:
  containers:
  - name: hello-world
    image: samber/hello-world-nodejs
    env:
      - name: PORT
        value: "8080"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: boostrap-1-service
  namespace: boostrap1
spec:
  type: NodePort
  selector:
    app: boostrap-1
  ports:
  - port: 18412
    targetPort: 8080
    nodePort: 30007